// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruwrnzizsffeswlhwquh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1d3Jueml6c2ZmZXN3bGh3cXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTM3NDIsImV4cCI6MjA2OTI4OTc0Mn0.ihfohhCXdbbJHIRX5LTOuwATYYpGyUeNt-ne-8uqUZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});